cirici_jwt_client_homepage:
    path:     /
    defaults: { _controller: CiriciJWTClientBundle:Default:index }

cirici_jwt_client_login:
    path: /login
    defaults: { _controller: CiriciJWTClientBundle:Security:login }

cirici_jwt_client_login_check:
    path: /login_check

cirici_jwt_client_logout:
    path: /logout
