services:
    project.token.user_provider:
        class: Cirici\JWTClientBundle\Security\TokenUserProvider
        calls:
            - [setUserClass, ['%api_user_class%']]

    project.token.jwt_verifier:
        class: Cirici\JWTClientBundle\Security\JwtVerifier
        arguments: ["%jwt_public_key_path%"]

    project.token.authenticator:
        class: Cirici\JWTClientBundle\Security\TokenAuthenticator
        arguments: ["@project.token.jwt_verifier", "@project.token.user_provider"]
