services:
    project.token.external_authenticator:
        class: Cirici\JWTClientBundle\Security\ExternalTokenAuthenticator
        arguments: ["@project.repository.api", "%jwt_public_key_path%", "@project.token.jwt_verifier"]
