services:
    project.repository.api:
        class: Cirici\JWTClientBundle\Repository\BaseRepository
        arguments: ["@guzzle.client.api_jwt", "@security.token_storage"]
    project.token.external_authenticator:
        class: Cirici\JWTClientBundle\Security\ExternalTokenAuthenticator
        arguments: ["@project.repository.api", "%jwt_public_key_path%", "@project.token.jwt_verifier"]
