services:
    project.repository.api:
        class: Cirici\JWTClientBundle\Repository\Api\BaseRepository
        arguments: ["%external_api%", "@security.token_storage", "%jwt_token_path%"]
    project.token.external_authenticator:
        class: Cirici\JWTClientBundle\Security\ExternalTokenAuthenticator
        arguments: ["@project.repository.api", "@project.token.jwt_verifier"]
