language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  global:
    - COVERAGE=0

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: SYMFONY_VERSION="2.8"
    - php: 7.0
      env: SYMFONY_VERSION="3.0" COVERAGE=1
  fast_finish: true


before_install:
  - if [[ $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update || true
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;


install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - sh -c "if [ '$COVERAGE' = '0' ]; then php ./vendor/bin/phpunit; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then php ./vendor/bin/phpunit --coverage-clover=clover.xml; fi"

after_success:
  - bash <(curl -s https://codecov.io/bash)
